### ISSUE TITLE
Coloris launches correctly, but will only display a blank window

### ISSUE THREAD

**Issue by ToniOS11** [Coraye/Alpha-releases#1]
After digging through what seemed like an eternity for affordable/free alternatives for a $500.00 purchase for Color Think Pro, I finally came across your app and by the looks of the screenshots on your website, has a lot of potential. However, I currently am unable to utilize it for anything as the app simply display an empty application window with the words "Teuf 2.1.0" in the top left corner. I downloaded the .DMG file as well as the .zip variant also and got the same result both times.

![Uploading Screen Shot 2018-02-18 at 7.18.51 PM.png…]()

**Comment by Calderis** [comment]
Hi @ToniOS11 !
Thanks a lot for your interest in Coloris. It's absolutly normal that nothing happen because we are currently developing the second version of Coloris. What you have in this repo will be releases of this version and what you downloaded is actually a test in order to check Github auto-update (yes we'll support that in the next release ;) )

We had closed the previous version in order to be focused on the next full version of Coloris. I'll keep you in touch if you want :) !

I did not see you issue before because I wasn't prepared to see one ^^'. Sorry for the delay though...

**Comment by Calderis** [comment]
So for the time being, Coloris can't be downloaded at all, wait a little more and subscribe to our newsletter to be informed of when does Coloris 2 will be ready : http://www.coloris-app.fr/downloads-closed/

You still can contact us by mail http://www.coloris-app.fr/contact-us/ or by answering this issues, I'll be more vigilant from now on ;)
